"""
Wiki renderer — generates docs/wiki/ from knowledge_map.json and corpus.db.

Usage:
  python -m crucible.wiki.renderer           — generate all wiki pages
  python -m crucible.wiki.renderer --page P  — generate a single page

Pages generated:
  docs/wiki/index.md          — project overview + stage summary
  docs/wiki/primitives.md     — domain primitives + signal map
  docs/wiki/amendments.md     — amendment log (from DB or amendments.md fallback)
  docs/wiki/stage_history.md  — stage closeout records
  docs/wiki/known_issues.md   — violations + failure modes from knowledge map
  docs/wiki/knowledge_graph.md — Mermaid diagram of knowledge_map.json
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

from crucible.export.redact import redact as _redact


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def _wiki_dir() -> Path:
    d = _repo_root() / 'docs' / 'wiki'
    d.mkdir(parents=True, exist_ok=True)
    return d


def _load_knowledge_map() -> dict:
    path = _repo_root() / 'docs' / 'knowledge_map.json'
    if not path.exists():
        return {'nodes': [], 'edges': []}
    return json.loads(path.read_text())


def _read_corpus(rel_path: str) -> str:
    path = _repo_root() / rel_path
    return path.read_text() if path.exists() else ''


def _amendments_from_db() -> list[dict]:
    try:
        from crucible.db.conn import get as get_conn
        conn = get_conn()
        rows = conn.execute('SELECT * FROM amendments ORDER BY number').fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _amendments_from_markdown() -> list[dict]:
    text = _read_corpus('docs/governance/amendments.md')
    out = []
    for m in re.finditer(r'### Amendment (\d+) — (.+)', text):
        number = int(m.group(1))
        title  = m.group(2).strip()
        block_start = m.start()
        next_m = re.search(r'### Amendment \d+', text[block_start + 1:])
        block = text[block_start: block_start + 1 + (next_m.start() if next_m else len(text))]
        status_m = re.search(r'Status:\s*(PROPOSED|RATIFIED)', block, re.IGNORECASE)
        status = status_m.group(1).upper() if status_m else 'PROPOSED'
        out.append({'number': number, 'title': title, 'status': status,
                    'ratified_date': None, 'traces_to': None})
    return out


def _render_knowledge_graph(km: dict) -> str:
    nodes = km.get('nodes', [])
    edges = km.get('edges', [])

    if not nodes:
        return '_Knowledge map is empty. Nodes are added as the project progresses._\n'

    lines = ['```mermaid', 'graph TD']

    type_styles = {
        'primitive':    'fill:#2d6a4f,color:#fff',
        'signal':       'fill:#1d3557,color:#fff',
        'threshold':    'fill:#e63946,color:#fff',
        'failure_mode': 'fill:#6d2b2b,color:#fff',
        'amendment':    'fill:#457b9d,color:#fff',
        'bill':         'fill:#a8dadc,color:#000',
        'test':         'fill:#f1faee,color:#000',
        'stage':        'fill:#e9c46a,color:#000',
    }

    for node in nodes:
        nid   = node['id'].replace(':', '_').replace('-', '_')
        label = node['label']
        unit  = f" [{node['unit']}]" if node.get('unit') else ''
        lines.append(f'  {nid}["{label}{unit}"]')

    for edge in edges:
        src = edge['source'].replace(':', '_').replace('-', '_')
        tgt = edge['target'].replace(':', '_').replace('-', '_')
        rel = edge.get('relation', '')
        lines.append(f'  {src} -->|{rel}| {tgt}')

    for node in nodes:
        nid   = node['id'].replace(':', '_').replace('-', '_')
        style = type_styles.get(node['type'], '')
        if style:
            lines.append(f'  style {nid} {style}')

    lines.append('```')
    return '\n'.join(lines) + '\n'


def render_index() -> str:
    device_ctx = _read_corpus('docs/device_context.md')

    purpose = ''
    target  = ''
    threshold = ''
    for line in device_ctx.splitlines():
        if line.startswith('**Project target:**'):
            target = line.replace('**Project target:**', '').strip()
        if line.startswith('**Pass/fail threshold:**'):
            threshold = line.replace('**Pass/fail threshold:**', '').strip()
        if '## Device Purpose' in line:
            purpose = '(see Device Purpose section)'

    amendments = _amendments_from_db() or _amendments_from_markdown()
    ratified = [a for a in amendments if str(a.get('status', '')).upper() == 'RATIFIED']

    now = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')
    return f"""# Project Wiki

_Generated by Crucible — {now}_

## Device

**Project target:** {target or '_Not yet defined_'}

**Pass/fail threshold:** {threshold or '_Not yet defined_'}

## Constitutional record

- Amendments ratified: **{len(ratified)}** of {len(amendments)}
- Most recent ratified: {ratified[-1]['title'] if ratified else '_none_'}

## Quick links

- [Domain Primitives](primitives.md)
- [Amendment Log](amendments.md)
- [Stage History](stage_history.md)
- [Known Issues](known_issues.md)
- [Knowledge Graph](knowledge_graph.md)
"""


def render_primitives() -> str:
    km = _load_knowledge_map()
    primitives = [n for n in km.get('nodes', []) if n['type'] == 'primitive']
    signals    = [n for n in km.get('nodes', []) if n['type'] == 'signal']
    edges      = km.get('edges', [])

    lines = ['# Domain Primitives\n']
    if not primitives:
        lines.append('_No primitives defined yet. Run `/spec collect` or `/spec fast`._\n')
        return '\n'.join(lines)

    for p in primitives:
        lines.append(f'## {p["label"]} ({p.get("unit", "—")})\n')
        if p.get('notes'):
            lines.append(p['notes'] + '\n')
        linked_signals = [
            s['label'] for s in signals
            if any(e['source'] == s['id'] and e['target'] == p['id']
                   and e['relation'] == 'traces_to' for e in edges)
        ]
        if linked_signals:
            lines.append('**Measured via:** ' + ', '.join(linked_signals) + '\n')
        lines.append('')

    return '\n'.join(lines)


def render_amendments() -> str:
    amendments = _amendments_from_db() or _amendments_from_markdown()
    lines = ['# Amendment Log\n',
             '| # | Title | Status | Traces to | Ratified |',
             '|---|-------|--------|-----------|---------|']
    for a in amendments:
        num    = a['number']
        title  = a['title']
        status = str(a.get('status', 'PROPOSED')).upper()
        traces = a.get('traces_to') or '—'
        date   = a.get('ratified_date') or '—'
        lines.append(f'| {num} | {title} | {status} | {traces} | {date} |')
    return '\n'.join(lines) + '\n'


def render_stage_history() -> str:
    root = _repo_root()
    closeouts = sorted((root / 'docs' / 'governance').glob('stage_*_closeout.md'))
    if not closeouts:
        return '# Stage History\n\n_No stages closed yet._\n'

    lines = ['# Stage History\n']
    for path in closeouts:
        lines.append(f'## {path.stem.replace("_", " ").title()}\n')
        text = path.read_text()
        first_card = text[:600]
        lines.append(first_card)
        lines.append(f'\n_[Full record]({path.relative_to(root / "docs")}})_\n')
    return '\n'.join(lines)


def render_known_issues() -> str:
    km = _load_knowledge_map()
    failures = [n for n in km.get('nodes', []) if n['type'] == 'failure_mode']

    lines = ['# Known Issues\n']
    if not failures:
        lines.append('_No failure modes recorded in knowledge map yet._\n')
        return '\n'.join(lines)

    for f in failures:
        lines.append(f'## {f["label"]}\n')
        if f.get('notes'):
            lines.append(f['notes'] + '\n')
        edges = [e for e in km.get('edges', []) if e['source'] == f['id']]
        for e in edges:
            lines.append(f'- **{e["relation"]}**: `{e["target"]}`')
            if e.get('evidence'):
                lines.append(f'  Evidence: {e["evidence"]}')
        lines.append('')

    return '\n'.join(lines)


def render_knowledge_graph() -> str:
    km = _load_knowledge_map()
    lines = ['# Knowledge Graph\n',
             '_Auto-generated from docs/knowledge_map.json_\n']
    lines.append(_render_knowledge_graph(km))
    return '\n'.join(lines)


PAGES = {
    'index':           ('index.md',           render_index),
    'primitives':      ('primitives.md',       render_primitives),
    'amendments':      ('amendments.md',       render_amendments),
    'stage_history':   ('stage_history.md',    render_stage_history),
    'known_issues':    ('known_issues.md',     render_known_issues),
    'knowledge_graph': ('knowledge_graph.md',  render_knowledge_graph),
}


def generate(page: Optional[str] = None, redact: bool = True) -> None:
    wiki = _wiki_dir()
    targets = {page: PAGES[page]} if page and page in PAGES else PAGES

    for name, (filename, renderer) in targets.items():
        content = renderer()
        if redact:
            content = _redact(content)
        (wiki / filename).write_text(content)
        print(f'  [OK] docs/wiki/{filename}')


# ─── CLI additions (Idea 5 / Error 16) ────────────────────────────────────────

def _summary() -> str:
    """ASCII corpus table — token-efficient alternative to full police check.

    ~200 tokens. Used by /wiki status and /session status (police token cost fix).
    """
    amendments = _amendments_from_db() or _amendments_from_markdown()
    root = _repo_root()

    # Parse hearings from MANIFEST.md
    hearings = []
    manifest = root / 'docs' / 'governance' / 'hearings' / 'MANIFEST.md'
    if manifest.exists():
        for line in manifest.read_text().splitlines():
            if not line.startswith('|') or line.startswith('| ID') or line.startswith('|---'):
                continue
            cols = [c.strip() for c in line.strip('|').split('|')]
            if len(cols) >= 7:
                hearings.append({
                    'id': cols[0], 'name': cols[1], 'date': cols[2],
                    'has_a': cols[4].upper() == 'TRUE',
                    'has_b': cols[5].upper() == 'TRUE',
                    'has_j': cols[6].upper() == 'TRUE',
                })

    # Build ASCII table
    lines = [
        '┌─── CORPUS SUMMARY ─────────────────────────────────────────────────────┐',
        '│ AMENDMENTS                                                              │',
        '├─────┬──────────────────────────────────────────┬────────────────────────┤',
        '│ #   │ Title                                    │ Status                 │',
        '├─────┼──────────────────────────────────────────┼────────────────────────┤',
    ]
    for a in amendments:
        num = str(a['number']).ljust(3)
        title = a['title'][:40].ljust(40)
        status = a.get('status', 'PROPOSED')[:22].ljust(22)
        lines.append(f'│ {num} │ {title} │ {status} │')
    lines.append('├─────┴──────────────────────────────────────────┴────────────────────────┤')
    lines.append('│ HEARINGS                                                                │')
    lines.append('├────────┬────────────────────────────────────┬──────┬───────────────────┤')
    lines.append('│ ID     │ Name                               │ Date │ A / B / J         │')
    lines.append('├────────┼────────────────────────────────────┼──────┼───────────────────┤')
    if hearings:
        for h in hearings:
            hid = h['id'][:6].ljust(6)
            name = h['name'][:34].ljust(34)
            date = h['date'][:6].ljust(6) if h['date'] else '      '
            flags = f"{'✓' if h['has_a'] else '✗'} / {'✓' if h['has_b'] else '✗'} / {'✓' if h['has_j'] else '✗'}"
            lines.append(f'│ {hid} │ {name} │ {date} │ {flags.ljust(17)} │')
    else:
        lines.append('│ (no hearings on record)                                                 │')
    lines.append('└────────────────────────────────────────────────────────────────────────────┘')
    return '\n'.join(lines)


def _wiki_primitive(name: str) -> str:
    """Print all corpus references to a domain primitive inline."""
    root = _repo_root()
    results = [f'## Corpus references: {name}\n']

    # Amendments
    amend_text = _read_corpus('docs/governance/amendments.md')
    if name.lower() in amend_text.lower():
        results.append('**Amendment references:**')
        for i, line in enumerate(amend_text.splitlines(), 1):
            if name.lower() in line.lower():
                results.append(f'  Line {i}: {line.strip()}')
        results.append('')

    # Hearings
    hearings_dir = root / 'docs' / 'governance' / 'hearings'
    if hearings_dir.exists():
        for hf in sorted(hearings_dir.glob('H-*.md')):
            text = hf.read_text()
            if name.lower() in text.lower():
                results.append(f'**Hearing {hf.stem}:** references {name}')

    # src/ Traces-to annotations
    src_dir = root / 'src'
    if src_dir.exists():
        for py in src_dir.glob('*.py'):
            text = py.read_text()
            for i, line in enumerate(text.splitlines(), 1):
                if 'traces to' in line.lower() and name.lower() in line.lower():
                    results.append(f'**{py.name}:{i}:** {line.strip()}')

    return '\n'.join(results) if len(results) > 1 else f'No corpus references found for: {name}'


def _wiki_hearing(hearing_id: str) -> str:
    """Print hearing summary + linked primitives + case law entry."""
    root = _repo_root()
    hearings_dir = root / 'docs' / 'governance' / 'hearings'

    # Find the hearing file
    hearing_file = None
    if hearings_dir.exists():
        matches = list(hearings_dir.glob(f'{hearing_id}*.md'))
        if matches:
            hearing_file = matches[0]

    if not hearing_file or not hearing_file.exists():
        return f'Hearing {hearing_id} not found in docs/governance/hearings/'

    text = hearing_file.read_text()
    has_a = bool(re.search(r'^##\s+Attorney[-\s]A\s+(argued|position)', text, re.IGNORECASE | re.MULTILINE))
    has_b = bool(re.search(r'^##\s+Attorney[-\s]B\s+(argued|position)', text, re.IGNORECASE | re.MULTILINE))
    has_j = bool(re.search(r'^##\s+Justice\s+(ruled|ruling)', text, re.IGNORECASE | re.MULTILINE))

    complete = '✓ COMPLETE' if (has_a and has_b and has_j) else '✗ INCOMPLETE'
    sections = f"A={'✓' if has_a else '✗'}  B={'✓' if has_b else '✗'}  J={'✓' if has_j else '✗'}"

    primitives_found = re.findall(r'\b[A-Z][a-z]+ [A-Z][a-z]+\b', text)

    lines = [
        f'## {hearing_id} — {hearing_file.stem}',
        f'Status: {complete}  ({sections})',
        '',
    ]

    # Extract ruling if present
    ruling_m = re.search(r'^##\s+Justice\s+rul\w+\s*\n+(.*?)(?=\n##|\Z)', text, re.IGNORECASE | re.MULTILINE | re.DOTALL)
    if ruling_m:
        ruling = ruling_m.group(1).strip()[:400]
        lines.append(f'**Ruling:**\n{ruling}')
        lines.append('')

    if primitives_found:
        lines.append(f'**Primitives referenced:** {", ".join(set(primitives_found[:5]))}')

    return '\n'.join(lines)


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description='Crucible wiki renderer and corpus query tool')
    parser.add_argument('--page', default=None,
                        choices=list(PAGES.keys()),
                        help='Generate a single wiki page')
    parser.add_argument('--no-redact', action='store_true',
                        help='Write raw corpus values (internal use only)')
    # Error 16 / Idea 5: corpus query flags
    parser.add_argument('--summary', action='store_true',
                        help='Print ASCII corpus summary table (~200 tokens). Use for /wiki status.')
    parser.add_argument('--wiki-primitive', metavar='NAME',
                        help='Print all corpus references to a domain primitive inline.')
    parser.add_argument('--wiki-hearing', metavar='H-NNN',
                        help='Print hearing summary + linked primitives + ruling.')
    args = parser.parse_args()

    if args.summary:
        print(_summary())
        return 0

    if args.wiki_primitive:
        print(_wiki_primitive(args.wiki_primitive))
        return 0

    if args.wiki_hearing:
        print(_wiki_hearing(args.wiki_hearing))
        return 0

    print('Generating wiki → docs/wiki/')
    generate(args.page, redact=not args.no_redact)
    return 0


if __name__ == '__main__':
    sys.exit(main())
